catalog:
  '@biomejs/biome': 2.2.2
  typescript: ^5.9.2

catalogs:
  node24:
    '@types/node': ^24.3.0
  react19:
    '@types/react': ^19.1.12
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
